services:
  # Service API Node.js
  api:
    build: 
      context: ./
      dockerfile: Dockerfile 
    restart: always
    ports:
      - "4002:4002"
    environment:
      - JWT_SECRET=your_jwt_secret=value
      - PORT=4002
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo 
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus   
      
  # Service MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: